### ISSUE TITLE
Unreadable content produced

### ISSUE THREAD

**Issue by vilinski** [geoplex/openxmlutils#1]
The examples from README.md and from test projects are producing some broken files. Excel says "unreadable content found" and tries to repair it. Looks like a problem with random time span and numerics

**Comment by dmcd** [comment]
Thanks vilinski, I was receiving "unreadable content found" when trying to open a spreadsheet with multiple sheets. I'm hoping that was the same issue you were seeing.

**Comment by vilinski** [comment]
Sorry but no, it is also with single songs.xlsx, and even with you last hour changes. Also if repaired, total sum works only for RandomInt column:
![image](https://cloud.githubusercontent.com/assets/259479/9684705/79393308-5319-11e5-9f3b-70d2a2d8a4b6.png)

**Comment by dmcd** [comment]
Interesting. What version of excel are you running and are you on Windows? I don't actually have a copy of excel for windows so I'm testing on Mac Office and Google spreadsheets. I'll try to test this on Windows soon.

<img width="994" alt="screen shot 2015-09-05 at 08 45 23" src="https://cloud.githubusercontent.com/assets/4025574/9695915/8d077f98-53aa-11e5-8707-97c2de4743fe.png">

**Comment by vilinski** [comment]
I have a german 2010 Excel on german Win7
